# Dockerfile-postgres
FROM postgres:13

# Tùy chọn: copy script init DB (nếu cần)
# COPY ./init.sql /docker-entrypoint-initdb.d/

# Set timezone (optional)
ENV TZ=Asia/Ho_Chi_Minh

# Expose default Postgres port
EXPOSE 5432